### PR TITLE
remove safe_yaml. Psych.safe_load is fine for modern rubies

### PR DESCRIPTION
**Pull request by bf4**
Otherwise webmock -> crack -> safe_yaml

### CODE REVIEW

**Comment by bf4** [comment]
Optionally, see https://github.com/sferik/rails_admin/pull/2397/files

**Comment by preston** [comment]
Yes, please!

**Comment by bf4** [comment]
@preston In the meantime, here's an example of what I have in my Gemfile

```ruby
  # RailsAdmin only uses safe_yaml when present https://github.com/sferik/rails_admin/pull/2397
  # SafeYaml, unfortunately, is included by webmock's dependency on crack
  gem 'crack', github: 'bf4/crack', branch: 'no_safe_yaml'
  gem 'webmock', '~>3.0.0'
```

**Comment by bf4** [comment]
@jnunemaker Oh wow, thanks!

**Comment by bf4** [comment]
@jnunemaker I just realized webmock is still pulling in safe_yaml through crack. Any chance we can bump this to 0.4.4?

**Comment by javierjulio** [comment]
Looks like this has been released now. Thanks!

**Pull request merged**
